#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jmock
Version  : 2.8.4
Release  : 1
URL      : https://github.com/jmock-developers/jmock-library/archive/2.8.4.tar.gz
Source0  : https://github.com/jmock-developers/jmock-library/archive/2.8.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jmock/jmock-parent/2.8.4/jmock-parent-2.8.4.pom
Source2  : https://repo1.maven.org/maven2/org/jmock/jmock-testjar/2.8.4/jmock-testjar-2.8.4.jar
Source3  : https://repo1.maven.org/maven2/org/jmock/jmock-testjar/2.8.4/jmock-testjar-2.8.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jmock-data = %{version}-%{release}

%description
[![Build Status](https://travis-ci.org/jmock-developers/jmock-library.svg?branch=jmock2)](https://travis-ci.org/jmock-developers/jmock-library)

%package data
Summary: data components for the mvn-jmock package.
Group: Data

%description data
data components for the mvn-jmock package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-parent/2.8.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-parent/2.8.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jmock/jmock-parent/2.8.4/jmock-parent-2.8.4.pom
/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4/jmock-testjar-2.8.4.jar
/usr/share/java/.m2/repository/org/jmock/jmock-testjar/2.8.4/jmock-testjar-2.8.4.pom
